- announce/2015/mfsa2015-08.md
In YAML a wrapped paragraph has to line up
indents. YAML was interpreting "extension" as a new
key without a ":" and was erroring.
> Fix word wrap in mfsa2015-08

- announce/2005/mfsa2005-57.md
- announce/2006/mfsa2006-30.md
- announce/2007/mfsa2007-10.md
- announce/2007/mfsa2007-38.md
- announce/2011/mfsa2011-17.md
- announce/2012/mfsa2012-01.md
- announce/2012/mfsa2012-19.md
- announce/2012/mfsa2012-20.md
- announce/2012/mfsa2012-42.md
- announce/2012/mfsa2012-57.md
- announce/2012/mfsa2012-59.md
- announce/2012/mfsa2012-74.md
- announce/2013/mfsa2013-104.md
- announce/2013/mfsa2013-21.md
- announce/2013/mfsa2013-30.md
- announce/2013/mfsa2013-41.md
- announce/2013/mfsa2013-63.md
- announce/2013/mfsa2013-76.md
- announce/2013/mfsa2013-93.md
- announce/2014/mfsa2014-01.md
- announce/2014/mfsa2014-15.md
- announce/2014/mfsa2014-34.md
- announce/2014/mfsa2014-48.md
- announce/2014/mfsa2014-56.md
- announce/2014/mfsa2014-67.md
- announce/2014/mfsa2014-74.md
- announce/2015/mfsa2015-30.md
- announce/2015/mfsa2015-41.md
- announce/2015/mfsa2015-44.md
1. I ran the advisory pool through my XML parser,  and it choked on a number of **obvious HTML bugs**. There is one commit to address all of these.
1. My link parser then stumbled across a sizable number of **malformed Bugzilla URLs**. This pull request addresses these, too. Some are particularly regular, having certain bug IDs prefixed with **&amp;#10;**, suggesting they were created by a **broken extraction or conversion script** incorrectly handling line breaks inside of URLs.
1. Lastly I found a line-broken *title* in the header of one advisory which later turned out to be the result of a **duplication of the title**, likely due to a copy&paste issue.
I touched two **advisory headers** to make them **consistent** with the rest:
1. One lonely advisory was using the **fix_released** …
> Please merge my cleanup commits (rebased version of closed pull request #3)

- announce/2014/mfsa2014-25.md
- announce/2015/mfsa2015-102.md
- announce/2015/mfsa2015-106.md
- announce/2015/mfsa2015-108.md
- announce/2015/mfsa2015-110.md
- announce/2015/mfsa2015-111.md
- announce/2015/mfsa2015-112.md
- announce/2015/mfsa2015-114.md
- announce/2015/mfsa2015-116.md
- announce/2015/mfsa2015-127.md
- announce/2015/mfsa2015-134.md
- announce/2015/mfsa2015-138.md
- announce/2015/mfsa2015-142.md
- announce/2015/mfsa2015-145.md
- announce/2015/mfsa2015-149.md
- announce/2015/mfsa2015-151.md
- announce/2015/mfsa2015-152.md
- announce/2015/mfsa2015-153.md
- announce/2015/mfsa2015-79.md
- announce/2015/mfsa2015-80.md
- announce/2015/mfsa2015-81.md
- announce/2015/mfsa2015-85.md
- announce/2015/mfsa2015-89.md
- announce/2015/mfsa2015-90.md
- announce/2015/mfsa2015-92.md
- announce/2015/mfsa2015-96.md
This PR not only includes the advisory pool changes for the 2.5 release, but also a bugfix for mfsa2014-25 which used "FirefoxOS" instead of the regular, white-spaced "Firefox OS" in its fixed_in field, making it appear in a different listing than the other FxOS-related advisories.
> Please merge advisories for FxOS 2.5

- announce/2016/mfsa2016-89.yml
- announce/2016/mfsa2016-90.yml
Fix a typo “Mozlla“ as well as capitalization, code, grammar.
> Fix some more issues on MFSA 2016-89 and 90

- announce/2017/mfsa2017-30.yml
Fix for the following error from the clock proc logs:
```
ERROR parsing /tmp/mofo_security_advisories/announce/2017/mfsa2017-30.yml: mapping values are not allowed here
in "/tmp/mofo_security_advisories/announce/2017/mfsa2017-30.yml", line 41, column 29
[2017-12-23 17:40:34.114568] Clock job update_security_advisories@bedrock-prod: CRASHED: Command 'python /app/manage.py update_security_advisories' returned non-zero exit status 1
```
> Wrap title in quotes due to unwrapped colon signifying map

- README.md
- bug-bounty-extract.py
- bug-bounty-hof/client.yml
- bug-bounty-hof/web.yml
- check_advisories.py
This is a work in progress, but I wanted to go ahead and get your eyes on the proposed file format. These files are the result of an extractor script I threw together to get the current data from the pages. More fields could be added to each entry as needed (like "product" mentioned in the bug) without interfering in page rendering, but name, date, and url will be the only fields that bedrock uses at first. I also added the dollar ammount from the top paragraph of each page to the data as I seem to recall that being updated from time to time as well. Let me know what you think.
> Bug 1435840: Add bug bounty hall of fame files

- check_advisories.py
bedrock breaks when it's not present[1], and this would have caught the
mistake fixed by commit 858ccec2c "fix yaml format error"
[1] https://github.com/mozilla/bedrock/blob/747ee3e649afc1317e1bb6f0909696d3c65c33ca/bedrock/security/management/commands/update_security_advisories.py#L147
> check_advisories: make the "bugs" field mandatory

- bug-bounty-hof/client.yml
- update_hof.py
Some of these were missing due to a mistake about the publish field,
others to a suspected file overlap date cutoff-related I-made-a-mistake
problem.
> Add more missing HOF entries back to the list.

- announce/2021/mfsa2021-13.yml
@tomrittervg it looks like the bug has the CVE alias, so I'm assuming MOZ here was a typo?
> Fix ID for bug 1666236

- announce/2015/mfsa2015-147.md
This URL was spotted as broken by a tool I'm creating for checking www.mozilla.org. I've removed the linebreak and confirmed via the Preview tab that it still works.
If this could be merged into master, that would be appreciated.
Equally, if this file is somehow autogenerated upstream, making any fix likely to be overwritten, do let me know. Thanks!
> Remove linebreak in URL to referenced Android commit

- announce/2013/mfsa2013-48.md
Spotted with a linkchecker tool being developed for mozilla.org - fixing this upstream means we don't need to add a special case to ignore it in the tool
> Fix incorrect parenthesis in href - link was 404ing

- bug-bounty-hof/client.yml
- bug-bounty-hof/web.yml
Hello @tomrittervg can you please check the PR? the missing mention was added to the client not the web HoF, thanks.
for reference, this is the bug for this mention https://bugzilla.mozilla.org/show_bug.cgi?id=1701644
> move mention from client to web HoF

- announce/2023/mfsa2023-06.yml
Firefox Focus doesn't ship from the ESR branch
> Remove CVE-2023-25743 from ESR 102.8 advisories

- announce/2023/mfsa2023-40.yml
- foundation_security_advisories/check_advisories.py
The latest advisory is currently being formatted weirdly because the products are all listed in one string with commas.
- So this PR fixes that for MFSA-2023-40
- And adds a check to `check_advisories` so it doesn't happen again
> Fix bad formatting of "Products" and "Fixed In" sections for latest advisory

- .github/workflows/pr.yml
- .github/workflows/push.yml
To make sure that the publish workflow isn't run on pull requests.
> Separate Push and Pull Request Workflows

- announce/2016/mfsa2016-85.yml
- announce/2016/mfsa2016-86.yml
- announce/2016/mfsa2016-87.yml
- announce/2016/mfsa2016-88.yml
- announce/2016/mfsa2016-89.yml
- announce/2017/mfsa2017-10.yml
- announce/2017/mfsa2017-18.yml
- announce/2017/mfsa2017-30.yml
- announce/2018/mfsa2018-11.yml
- announce/2021/mfsa2021-03.yml
- announce/2021/mfsa2021-07.yml
- announce/2021/mfsa2021-23.yml
- announce/2021/mfsa2021-24.yml
- announce/2021/mfsa2021-26.yml
- announce/2021/mfsa2021-38.yml
- announce/2021/mfsa2021-39.yml
- announce/2021/mfsa2021-40.yml
- announce/2021/mfsa2021-41.yml
- announce/2021/mfsa2021-42.yml
- announce/2022/mfsa2022-24.yml
- announce/2022/mfsa2022-25.yml
- announce/2022/mfsa2022-26.yml
- announce/2022/mfsa2022-28.yml
- announce/2022/mfsa2022-30.yml
- announce/2022/mfsa2022-32.yml
- announce/2023/mfsa2023-22.yml
- foundation_security_advisories/check_advisories.py
- foundation_security_advisories/common_cve.py
- Check that the title doesn't contain `<code>` tags or backticks
- Check that titles which contain a colon are surrounded by quotes
- Check that the description only contains basic html tags that should be used for formatting the description
Closes https://github.com/mozilla/foundation-security-advisories/issues/136
> Improve formatting checks arround advisory titles and descriptions 

- foundation_security_advisories/common_cve.py
If CVE services already have a reference with the same url as one that we have locally, do not add it again. This should prevent future issues like this failed CI run: https://github.com/mozilla/foundation-security-advisories/actions/runs/8756949809/job/24034559124 (I have already corrected this particular problem manually).
> Add additional check to prevent duplicate references

- announce/2025/mfsa2025-10.yml
- announce/2025/mfsa2025-11.yml
The use of "browser or browser-like environments" and "browser or browser-like contexts" could lead to confusion among users. This makes that sentence more clear.
This also adds the description update to the latest Thunderbird monthly release in mfsa2025-11.yml.
Thanks to Dan Veditz for the suggestion.
> Clarify browser contexts in Thunderbird description

- announce/2025/mfsa2025-24.yml
Unlike Firefox, Thunderbird doesn't seem to use ESR for 128 versions. cf https://github.com/mozilla/foundation-security-advisories/blob/f53088fa08e0b80226a41f69cc592229e6215908/announce/2025/mfsa2025-18.yml#L5C1-L5C20
> Thunderbird does not use ESR probably

- announce/2016/mfsa2016-86.yml
According to https://www.cve.org/CVERecord?id=CVE-2016-5272, the bugzilla id should be 1297934. https://bugzilla.mozilla.org/show_bug.cgi?id=1297934
> Correct bug id in mfsa2016-86.yml

- announce/2025/mfsa2025-45.yml
- announce/2025/mfsa2025-46.yml
- foundation_security_advisories/common_cve.py
We still have some issues with publishing CVEs that I wasn't able to fix in #157. These all stem from CVE-2025-5262, where we accidentally reserved and published a CVE and rejected it afterward.
- Fix a second possibly undefined key I missed in https://github.com/mozilla/foundation-security-advisories/pull/157
- If we own a CVE, but it is rejected like is the case with CVE-2025-5262, do not try to publish it
- Finally, also replace the rejected CVE-2025-5262 with CVE-2025-5283
> Fix issues caused by CVE-2025-5262

- foundation_security_advisories/common_cve.py
Add a dry run mode that limits the API calls to be read-only, skipping all the calls that would change content. I used this to verify the changes in #158 work correctly.
> Add DRY_RUN mode

- announce/2024/mfsa2024-29.yml
The OS is either actually called "macOS" or in the old variant with spaces as "Mac OS X". As newer advisories using "macOS" adjusting the file accordingly for consistency reasons.
> Change "mac OS" to "macOS" in mfsa2024-29.yml
